branches:
  except:
    - master

sudo: required

services:
  - docker

env:
  global:
    - CLOUDSDK_CORE_DISABLE_PROMPTS: 1

language: go
go:
  - "1.11.1"

install: go get ./...

script:
  - make lint test build

deploy:
  provider: script
  skip_cleanup: true
  script: .travis/deploy.sh
  on:
    tags: true
