version: '3'
services:
  fizzbuzz:
    build: .
    ports:
      - "8080:8080"
    environment:
      - "REDIS_ADDR=redis:6379"
      - "APP_PORT=8080"
      - "MAX_LIMIT=1024"
  redis:
    image: "redis:alpine"
